/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jbdubois.metro;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int border=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int metro=0x7f020002;
        public static final int noctilien=0x7f020003;
        public static final int noctilienlogo=0x7f020004;
        public static final int rer=0x7f020005;
        public static final int rerlogo=0x7f020006;
        public static final int zoomin=0x7f020007;
        public static final int zoomout=0x7f020008;
    }
    public static final class id {
        public static final int mainlayout=0x7f060000;
        public static final int metroImage=0x7f060001;
        public static final int zoomIn=0x7f060004;
        public static final int zoomOut=0x7f060003;
        public static final int zoomview=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int descr=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
}
